server:
  port: 8081

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

      # Чтобы убедиться, что JPA создаёт таблицы под твою модель
      sql:
        init:
          mode: always